[package]
name = "rustory"
description = "Disk usage monitoring tool written in Rust."
license = "MIT"
version = "0.1.0"
authors = ["Henrik Hedlund Andersen <heheand@gmail.com>"]
edition = "2018"

[dependencies]
